version: '3.8'
services:

  mongodb:
    container_name: taskmanager-mongodb
    restart: always
    build: 
      context: .
      dockerfile: ./docker/mongodb/Dockerfile
      args:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminPassword
      - MONGO_INITDB_DATABASE=task-manager-api
    ports: # enabled for accessing the database on @loclhost:27017 for testing purposes. The docker private network is used for communication between the api and db.
      - 27017:27017

  tasks-api:
    container_name: taskmanager-api
    restart: always
    build: 
      context: .
      dockerfile: ./docker/taskmanager-api/Dockerfile
    environment:
      - NODE_ENV=production
      # - PORT=3000
      # - SENDGRID_API_KEY=put-your-api-key-here
      # - JWT_SECRET=aComplicatedPassphraseHere
      # - MONGODB_URL=mongodb://myuser:mypassword@taskmanager-mongodb:27017/task-manager-api
    env_file: # env_file for API keys, rather than hardcoding above during development.
      - config/dev.env
    depends_on:
      - mongodb

  nginx-proxy:
    container_name: taskmanager-proxy
    restart: always
    build: 
      context: .
      dockerfile: ./docker/proxy/Dockerfile
    ports:
      - "8080:8080"